# Generated by Django 2.2.7 on 2019-11-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='type',
            new_name='member_type',
        ),
    ]
