# Generated by Django 2.2.7 on 2019-11-29 14:03

import contest_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0001_squashed_0004_auto_20191129_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member_type',
            field=models.CharField(choices=[(contest_app.models.MemberTypeEnum('Contender'), 'Contender'), (contest_app.models.MemberTypeEnum('Jury'), 'Jury'), (contest_app.models.MemberTypeEnum('Organizer'), 'Organizer')], max_length=25),
        ),
    ]
