# Generated by Django 2.2.7 on 2019-11-28 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0002_auto_20191128_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_no', models.IntegerField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest_app.Contest')),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='contest',
        ),
        migrations.AlterField(
            model_name='vote',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest_app.Stage'),
        ),
    ]
