# Generated by Django 2.2.7 on 2019-11-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0003_auto_20191128_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
